name: Check College Attendance

on:
  schedule:
    - cron: '0 3 * * *'    # 8:30 AM IST
    - cron: '0 11 * * *'   # 4:30 PM IST
  workflow_dispatch:       # allows manual trigger

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Attendance Bot
        run: python main.py
        env:
          COLLEGE_USER: ${{ secrets.COLLEGE_USER }}
          COLLEGE_PASS: ${{ secrets.COLLEGE_PASS }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          MY_PHONE_NUMBER: ${{ secrets.MY_PHONE_NUMBER }}
